version: '3.9'

services:
  app:
    build: .
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - 0.0.0.0:8000:80
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      PGUSER: ${DATABASE_USERNAME:-postgres}
      PGDATABASE: ${DATABASE_NAME:-postgres}
      PGPASSWORD: ${DATABASE_PASSWORD:-password}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT:-5432}:5432
    restart: always

volumes:
  db_data: