# Generated by Django 4.1.7 on 2023-05-11 15:55

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("DESIGN", "Design"),
                            ("CUSTOMER SUCCESS", "Customer Success"),
                            ("SOFTWARE DEVELOPER", "Software Developer"),
                        ],
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, max_length=1024)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("FULL TIME", "Full time"),
                            ("PART TIME", "Part time"),
                        ],
                        max_length=64,
                    ),
                ),
                ("min_salary", models.PositiveIntegerField()),
                ("max_salary", models.PositiveIntegerField()),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                ("city", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vacancy",
                "verbose_name_plural": "Vacancies",
            },
        ),
    ]
