# Generated by Django 4.1.7 on 2023-05-12 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(default="Developer", max_length=128)),
            ],
            options={
                "verbose_name": "Profession",
                "verbose_name_plural": "Professions",
            },
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="profession",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="careers.profession",
            ),
        ),
    ]
