# Generated by Django 4.1.7 on 2023-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0002_profession_alter_vacancy_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
