# Generated by Django 4.1.7 on 2023-05-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0003_vacancy_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="shift",
            field=models.CharField(
                choices=[("Full time", "Full time"), ("Part time", "Part time")],
                max_length=64,
            ),
        ),
    ]
