# Generated by Django 4.1.7 on 2023-05-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrequest',
            options={'verbose_name': 'Access Request', 'verbose_name_plural': 'Access Requests'},
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'verbose_name': 'Contact Request', 'verbose_name_plural': 'Contact Requests'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='use_case',
            field=models.TextField(max_length=1024),
        ),
    ]
