# Generated by Django 4.1.7 on 2023-05-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_profession"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=512)),
                ("answer", models.TextField(max_length=2048)),
            ],
            options={
                "verbose_name": "Frequently asked question",
                "verbose_name_plural": "Frequently asked questions",
            },
        ),
    ]
