# Generated by Django 4.1.7 on 2023-05-10 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(max_length=128)),
                ('work_email', models.EmailField(max_length=128)),
                ('interested_product', models.CharField(max_length=128)),
                ('tarx_plan', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('team_member', models.CharField(max_length=128)),
                ('problems_solve', models.CharField(max_length=1024)),
            ],
        ),
    ]
