# Generated by Django 4.1.7 on 2023-05-16 11:22

import colorfield.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=128)),
                (
                    "background_color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "text_color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=18, samples=None
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="posts", to="blog.tag"),
        ),
    ]
