# Generated by Django 4.1.7 on 2023-05-10 13:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='url_height', upload_to=blog.models.update_filename, width_field='url_width'),
        ),
    ]
