name: CI

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  flake8:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          python3.11 -m venv env
          source env/bin/activate
      - name: Install packages
        run: |
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --statistics

  build:
    needs: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tarxismagic/tarx-cms:staging

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: pragnakalp
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/staging
            cd tarx_staging_
            dcdn
            dco pull
            dcup -d --force-recreate
            docker image prune
