name: CI

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          python3.11 -m venv env
          source env/bin/activate
      - name: Install packages
        run: |
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --statistics
